# --- stable options ---
array_width = 60
attr_fn_like_width = 60
chain_width = 60
disable_all_formatting = false
edition = "2024"
fn_call_width = 60
fn_params_layout = "Tall"
force_explicit_abi = true
hard_tabs = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 10
single_line_if_else_max_width = 60
single_line_let_else_max_width = 60
struct_lit_width = 60
struct_variant_width = 60
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
